### ISSUE TITLE
undefined styled.a crashes chat

### ISSUE THREAD

**Issue by loganallenc** [urbit/indigo-react#21]
<img width="500" alt="Screen Shot 2019-09-17 at 4 24 51 PM" src="https://user-images.githubusercontent.com/1377557/65086741-ca46b080-d967-11e9-85a5-6de0cf1f412f.png">

**Comment by jyng** [comment]
The give some more context. We were running urbit/interface/chat and we found that it might be something in styled components or system systems.I'll give you a fuller digest tmrw — I'm going to try running this again on my machine tomorrow to reproduce.

**Comment by jyng** [comment]
I'm archiving this issue until indigo-react because this is a higher-level decision about devDependencies
