### ISSUE TITLE
Noisy console.log behavior

### ISSUE THREAD

**Issue by Fang-** [urbit/indigo-react#62]
Was trying to see if I could get some useful information from web console about an issue I was experiencing, but couldn't find anything because there was an overwhelming amount of this:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/3829764/93613509-4176b080-f9d1-11ea-919b-c71072ac3d9e.png">

Guessing from the source file that this is baked in here.

**Comment by g-a-v-i-n** [comment]
Which version are you on?

**Comment by matildepark** [comment]
Landscape is currently on 1.1.15.

**Comment by g-a-v-i-n** [comment]
Thanks, it should be resolved in 1.2.x.

**Comment by g-a-v-i-n** [comment]
Closing because resolved in 1.2.x
