### ISSUE TITLE
textOverflow and whiteSpace not passed to Text component

### ISSUE THREAD

**Issue by matildepark** [urbit/indigo-react#79]
Tried putting a PR in to migrate to 1.2.10 but seeing that while textOverflow and whiteSpace are indeed shown as props, they're not being applied in the CSS styles. Was wondering if my cache was borked, but I can load the Server icon, so it seems to indeed be 1.2.10. (Pushed my branch on urbit/urbit to `mp/interface/indigo-react-1-2-10` if you want to look.)

<img width="271" alt="image" src="https://user-images.githubusercontent.com/20846414/96530433-6e7ae500-1255-11eb-981e-8021c8822c53.png">

**Comment by g-a-v-i-n** [comment]
Resolved in 1.2.13
