### ISSUE TITLE
indigo-dark base black too dark?

### ISSUE THREAD

**Issue by matildepark** [urbit/indigo-react#83]
testing out pulling off the bandages and it just feels like the theme is mixed odd, will supply a working branch once my chat PR is pushed in

<img width="1522" alt="Screen Shot 2020-11-09 at 9 41 10 PM" src="https://user-images.githubusercontent.com/20846414/98621051-736f0980-22d4-11eb-9e2d-e2c6de46de19.png">
<img width="1522" alt="Screen Shot 2020-11-09 at 9 41 13 PM" src="https://user-images.githubusercontent.com/20846414/98621052-7407a000-22d4-11eb-94e7-3273bdbd6c0e.png">

**Comment by matildepark** [comment]
OK this lives at `mp/landscape/indigo-themes` for inspection

**Comment by tacryt-socryp** [comment]
Wow this looks incredible

**Comment by urcades** [comment]
The first reaction I have to this is that the pure black `black100` is quite an extreme look: This approach makes sense when one takes into consideration OLED screens and the like (pure black interfaces are battery-saving), but I'd be interested in us seeing a bump down in the black used, aka `black90`.

This said, in many applications/apps, you often see preferences allowing a 'day', 'night (lower contrast)', and 'oled (higher contrast)' setting. This could be a nice affordance for our mobile users.

The greater (and actual/non-preference-based) issue here is obviously our borders surrounding interactive elements being destroyed/made invisible somehow. It'd be good to retain these for our dark theme, so interactive elements are more obvious.

**Comment by g-a-v-i-n** [comment]
- This is the exact purpose of themes.
- This change should be scoped to the theme, not the color assignment on the component.
- I think the black is too dark. In the theme, I would set the 'black' value to #1A1A1A, which is black90 mixed on a white bg.

**Comment by matildepark** [comment]
I mean ... this is about the theme, not the colour assignment? I'm confused. All I did was swap out the themes in our theme folder for the imported themes.

**Comment by matildepark** [comment]
Specifically https://github.com/urbit/urbit/commit/2005604c9d06abf10396fe4210f25ba1a4309125

**Comment by g-a-v-i-n** [comment]
Oh I see. I would just PR indigo-dark with black changed to #1A1A1A.

**Comment by g-a-v-i-n** [comment]
Or I can just do it now
