### ISSUE TITLE
safari spinner

### ISSUE THREAD

**Issue by tylershuster** [urbit/indigo-react#88]
Safari 14, Big Sur, on initial load:

![Screen Recording 2020-11-26 at 9 22 06 AM](https://user-images.githubusercontent.com/3999320/100379000-07c1b780-2fc9-11eb-8e2c-3ed0d1ef8849.gif)

This issue occurs across the board, for example upon uploading a file

**Comment by tylershuster** [comment]
https://bugs.webkit.org/show_bug.cgi?id=174285

**Comment by g-a-v-i-n** [comment]
I can't seem to repro this

**Comment by tylershuster** [comment]
Which version of Safari? I'm on 14.0.2 and I can't *not* reproduce it

**Comment by g-a-v-i-n** [comment]
I'm also on 14.0.2
<img width="387" alt="Screen Shot 2021-01-20 at 11 33 18 AM" src="https://user-images.githubusercontent.com/5265021/105225378-53996480-5b13-11eb-9358-5940c4e4e712.png">

**Comment by g-a-v-i-n** [comment]
any more context here? what is the position of the container?

**Comment by tylershuster** [comment]
A reliable way to test this for me is to join one of the dead channels in UC:

https://user-images.githubusercontent.com/3999320/105225669-c1de2700-5b13-11eb-9850-eac2c3556e45.mov

It occurs everywhere this component is used:

https://github.com/urbit/urbit/blob/master/pkg/interface/src/views/components/Spinner.js

**Comment by urcades** [comment]
This is an ancient issue, but commenting now to call to attention that the observed behavior occurs when one is either zoomed in/out of the default 100% zoom level in safari. "Zooming" breaks the spinner's styling regardless of the direction one zooms in.

**Comment by g-a-v-i-n** [comment]
Ok this obviously deserves a much closer look

**Comment by g-a-v-i-n** [comment]
resolved in 1.2.20
