### ISSUE TITLE
Posts: We need a design for a "Posts" or "Group Feed" icon, for representing references to posts made to the feed

### ISSUE THREAD

**Issue by urcades** [urbit/indigo-react#97]
(Copying this over wholesale from Landscape, where I first wrote it — my apologies)

Now that references are available, we use an icon to refer to the resource type that the reference is pointing to:

<img width="180" alt="Screen Shot 2021-03-25 at 3 30 27 PM" src="https://user-images.githubusercontent.com/1195363/112532309-10f84080-8d7f-11eb-90d0-d7776ea85386.png">

Ideally, this icon is simply representative of the channel type that is being referenced.

We now need one for Posts, since we don't have one specified in Indigo atm — this is slightly pressing because we're encountering a bug breaks an entire group + notifications if an icon is missing. We're using a placeholder now, but should design something real, soon

ccing @g-a-v-i-n on this, since he's the Don of Indigo, but also ccing @jyng due to posts ownership

Breaking issue is here: https://github.com/urbit/landscape/issues/642

**Comment by g-a-v-i-n** [comment]
closing because this is an indigo issue not specific to indigo-react
