### ISSUE TITLE
request: decide on which "gray value" is the de-facto description of lightgray and washedgray

### ISSUE THREAD

**Issue by urcades** [urbit/indigo-react#98]
Howdy, dropping in here to mention that the `lightgray`/`black20` and `washedgray`/`black04` we use in Figma is currently not reflected in indigo-react, which is visible via the current developer testnet (check the red annotations):

<img width="1261" alt="Screen Shot 2021-03-30 at 3 29 16 AM" src="https://user-images.githubusercontent.com/1195363/112950381-39c66000-9108-11eb-9d21-b38392680f1f.png">

As it stands, it appears that we define `lightgray` in "indigo-react" as `black30` and `washedgray` as `black05` in indigo-light:

https://github.com/urbit/indigo-light/blob/master/index.ts#L94-L95

This is all to say, I really do love the way `black20` and `black04` appear onscreen. The difference is very subtle, but there is a 'starkness' to the currently-defined approach in indigo-react that causes the interface to appear overly-stroked or line-heavy:

indigo-react:

<img width="329" alt="Screen Shot 2021-03-30 at 3 25 59 AM" src="https://user-images.githubusercontent.com/1195363/112951271-2bc50f00-9109-11eb-8b73-b8bbd7b09b22.png">

figma indigo:

<img width="282" alt="Screen Shot 2021-03-30 at 3 26 23 AM" src="https://user-images.githubusercontent.com/1195363/112951300-32538680-9109-11eb-99a6-c4f2a2739d78.png">

**Comment by urcades** [comment]
The summation of my perspective here is that we've been using figma's version of indigo's color rules, and they look very good, and support (as far as I'm aware) the contrast necessary for properly distinguishing elements on-screen.

If this is all correct, we should move indigo-react to use the `black/white20` and `black/white04` definition of `light` and `washed` grays.

**Comment by g-a-v-i-n** [comment]
Yeah, this is annoying I will fix

**Comment by g-a-v-i-n** [comment]
Closing because I merged your PR
